channels:
    - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - setuptools
  - sympy
  - scipy
  - ipywidgets
  - jupyter_contrib_nbextensions
  - octave_kernel
  - pip
  - jupyterlab
  - pip:
    - jupyterlab_latex
