channels:
    - conda-forge
dependencies:
  - python
  - os
  - pandas
  - io
  - requests
  - matplotlib
  - numpy
  - setuptools
  - sympy
  - scipy
  - sklearn
  - statsmodels
  - seaborn
  - inspect
  - platform
  - ipywidgets
  - jupyter_contrib_nbextensions
  - octave_kernel
  - pip
  - jupyterlab
  - pip:
    - jupyterlab_latex
