.libPaths( c( "~/R/packages", .libPaths()) )

# packages from original publication
mypackages <- c("Hmisc", "tidyverse", "GGally", "car", "interplot", "interflex", "gridExtra", "coefplot", "psych")
# packages for binder
mypackages2 <- c("IRdisplay", "devtools")
install.packages(mypackages, lib="~/R/packages", verbose=TRUE)
install.packages(mypackages2, lib="~/R/packages", verbose=TRUE)
devtools::install_github('IRkernel/IRkernel', lib="~/R/packages")
IRkernel::installspec(user=TRUE,rprofile="~/.Rprofile")

install.packages("tidyverse", lib="~/R/packages")
install.packages("rmarkdown", lib="~/R/packages")
install.packages("httr", lib="~/R/packages")
install.packages("shinydashboard", lib="~/R/packages")
install.packages("leaflet", lib="~/R/packages")
install.packages("repr", lib="~/R/packages")
install.packages("IRdisplay", lib="~/R/packages")
install.packages("evaluate", lib="~/R/packages")
install.packages("crayon", lib="~/R/packages")
install.packages("pbdZMQ", lib="~/R/packages")
install.packages("devtools", lib="~/R/packages")
install.packages("uuid", lib="~/R/packages")
install.packages("digest", lib="~/R/packages")
devtools::install_github('IRkernel/IRkernel', lib="~/R/packages")
IRkernel::installspec(user=TRUE,rprofile="~/.Rprofile")
